## 自定义层
构造一个没有任何参数的自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

## 将层作为组件合并到构造更复杂的模型中

In [14]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.2596e-09, grad_fn=<MeanBackward0>)

## 带参数的图层

In [16]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[0.0585, 0.5721, 0.2285],
        [0.6098, 0.8056, 0.6340],
        [0.2447, 0.0065, 0.5389],
        [0.8696, 0.4240, 0.2260],
        [0.1010, 0.3819, 0.3550]], requires_grad=True)

## 使用自定义层直接执行正向传播计算

In [18]:
dense(torch.rand(2, 5))

tensor([[0.0000, 1.0677, 0.8176],
        [0.0000, 0.5808, 0.4351]])

## 使用自定义层构建模型

In [44]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[50.1582],
        [56.5296]])