## 读写文件

加载和保存张量

In [6]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
filename = '../data/test-x-file'
torch.save(x, filename)
y = torch.load(filename)
x == y

tensor([True, True, True, True])

## 存储一个张量列表再读回内存

In [8]:
y = torch.zeros(4)
torch.save([x, y], filename)
x2, y2 = torch.load(filename)
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

## 写入或读取从字符串隐射到张量的字典

In [11]:
mydict = {'x': x, 'y': y}
torch.save(mydict, filename)
mydict2 = torch.load(filename)
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 加载和保存模型参数

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
        
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

## 将模型的参数存储为一个叫"mlp.params"的文件

In [16]:
torch.save(net.state_dict(), 'mlp.params')

## 实例化了原始多层感知机模型的一个备份，直接读取内存中存储的参数

In [17]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [18]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])