## 张量表示一个数值组成的数组，这个数组可能有多个维度

In [36]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 我们可以通过张量的```shape```属性来访问张量的形状和张量中元素的总数

In [7]:
x.shape

torch.Size([12])

In [10]:
# 元素的种数量(number of elements)
x.numel()

12

## 改变张量的形状而不改变数量和元素值，可以通过调用```reshape```函数(```reshape```后张量中元素的改变会影响原来被```reshape```的张量的元素的值)

In [12]:
x.reshape(3, 4)
# 改为3行4列

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## 使用全0、全1、其它常量或者从特定分布中随机采样的数字

In [13]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torch.ones((2, 3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## 从python列表创建张量

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2,3, 4],[4, 3, 2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 常见的标准运算（+、-、\*、/和指数(**)）都可以被升级为按元素运算

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2,   2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

## 指数运算($e^n$) 


In [19]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 连接多个张量

In [22]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
Y = torch.tensor([[2.0, 1, 4,3], [1, 2,3, 4], [4, 3, 2,1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [26]:
# 在第0维合并(也就是在行合并)
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [29]:
# 在第1维合并（在列方向合并)
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

## 通过逻辑运算符构建二维张量

In [30]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [31]:
X.sum()

tensor(66.)

## 相同维度的两个张量，即使形状不同，也可以通过调用广播机制（broading mechanism）来执行按元素操作

In [34]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [35]:
# 本质是通过补全缺失的数据
# 对张量a复制第一列，使其具有两列，对张量b，复制第一行，使其具有两行
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 使用```[-1]```选择最后一个元素，用```[1:3]```选择第二个和第三个元素

In [38]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

## 通过指定索引来将元素写入张量

In [40]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

## 为多个元素赋予相同的值

In [43]:
# 选中第0、1行中的所有列, 赋值为12
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 运行一些操作可能导致为新结果分配内存

In [48]:
# id函数类似于获取对象的地址
before = id(Y)
Y = Y + X
# 地址不同了
id(Y) == before

False

## 执行原地操作

In [51]:
Z = torch.zeros_like(Y)
print("id(Z): ", id(Z))
Z[:] = X + Y
print("id(Z): ", id(Z))

id(Z):  140654555647328
id(Z):  140654555647328


## 如果在后续操作中不在使用的某个张量，可以直接改写，减少内存的分配

In [55]:
before = id(X)
X += Y
id(X) == before
X

tensor([[64., 62., 68., 66.],
        [62., 64., 66., 68.],
        [48., 51., 54., 57.]])

## 转换为Numpy张量

In [56]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

## 将大小为1的张量转换为Python的标量

In [57]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)