## 标量由只有一个元素的张量表示

In [2]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y,  x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 可将向量视为标量值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

## 访问张量的长度

In [5]:
len(x)

4

## 只有一个轴的张量，形状只有一个元素

In [6]:
x.shape

torch.Size([4])

## 通过指定两个分量$m$和$n$来创建一个形状为$m \times n$的矩阵

In [8]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## 矩阵的转置(按照对角线翻转)

In [9]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 对称矩阵（symmetric matrix）$A$等于其转置: $A=A^T$

In [10]:
B = torch.tensor([[1,2,3], [2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建更多轴的数据结构

In [13]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 给定具有相同形状的任何两个张量，任何按元素二元计算的结果都将是相同形状的张量

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 分配新内存，将一个A的副本给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 两个矩阵按元素的乘法称为```哈达玛积（Hadamard product）``` （数学符号$\odot$）

In [16]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

## 张量和标量的运算

In [18]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 计算其元素的和

In [19]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

## 表示任意形状的元素和

In [21]:
A = torch.arange(20*2).reshape(2, 5,4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))