## 标量由只有一个元素的张量表示

In [2]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y,  x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 可将向量视为标量值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

## 访问张量的长度

In [5]:
len(x)

4

## 只有一个轴的张量，形状只有一个元素

In [6]:
x.shape

torch.Size([4])

## 通过指定两个分量$m$和$n$来创建一个形状为$m \times n$的矩阵

In [8]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## 矩阵的转置(按照对角线翻转)

In [9]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 对称矩阵（symmetric matrix）$A$等于其转置: $A=A^T$

In [10]:
B = torch.tensor([[1,2,3], [2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建更多轴的数据结构

In [13]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 给定具有相同形状的任何两个张量，任何按元素二元计算的结果都将是相同形状的张量

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 分配新内存，将一个A的副本给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 两个矩阵按元素的乘法称为```哈达玛积（Hadamard product）``` （数学符号$\odot$）

In [16]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

## 张量和标量的运算

In [18]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 计算其元素的和

In [19]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

## 表示任意形状的元素和

In [25]:
A = torch.arange(20*2).reshape(2, 5,4)
A.shape, A.sum(), A

(torch.Size([2, 5, 4]),
 tensor(780),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]))

## 指定求和汇总张量的轴(按哪个维度求就是消除哪个维度)

In [24]:
A_sum_axis_0= A.sum(axis=0)
A_sum_axis_0, A_sum_axis_0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [28]:
A_sum_axis_1 = A.sum(axis=1)
A_sum_axis_1, A_sum_axis_1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [30]:
# 两个维度求和
A_sum_axis_01 = A.sum(axis=[0, 1])
A_sum_axis_01

tensor([180, 190, 200, 210])

## 与求和相关的量：*均值*（mean或average)
## 张量的数据类型需要为浮点数

In [52]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2, 5,4)
A, A.mean(), A.sum() / A.numel()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor(19.5000),
 tensor(19.5000))

## 与求和类似，也可以按维度求平均

In [56]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0], A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 2)

## 计算总和或均值保持维度不变

In [58]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A, sum_A.shape

(tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 torch.Size([1, 5, 4]))

In [59]:
sum_A_1 = A.sum(axis=1, keepdims=True)
sum_A_1, sum_A_1.shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

## 通过广播将```A```除以```sum_A```（不同维度无法广播）

In [60]:
A.shape, sum_A.shape

(torch.Size([2, 5, 4]), torch.Size([1, 5, 4]))

In [61]:
A / sum_A 

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

## 某个轴计算```A```元素的累计总和

In [67]:
A, A.cumsum(axis=0)


(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]))

In [65]:
B = torch.arange(20).reshape(5,4)
B

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [66]:
B.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

## 点积是相同位置的按元素乘积的和

In [69]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 可以通过按元素乘法，然后进行求和来表示两个向量的点积

In [70]:
ts = torch.sum(x * y)
x, y, ts

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 矩阵向量积$Ax$是一个长度为$m$的列向量，其$i^{th}$元素是点积$A_i^TX$

In [97]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A, x)
# mv 表示 matrix-vector
A.shape, x.shape, torch.mv(A, x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([0., 1., 2., 3.])


(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 我们可以将矩阵-矩阵乘法$AB$看做是简单地执行$m$次矩阵-向量积，并将结果拼接在一起，形成一个$n \times m$矩阵

In [100]:
B = torch.ones(4, 3)
print(A, B)
torch.mm(A, B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## $L_2$范数是向量元素平方和的平方根

$$
\begin{Vmatrix}
X
\end{Vmatrix}_2 = \sqrt{\sum_{i=1}^{n}{x_i^2}}
$$

In [104]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

## $L_1$范数是向量元素的绝对值之和
$$
\begin{Vmatrix}
X
\end{Vmatrix}_1 = \sum_{i=1}^{n}|{x_i}|
$$

In [106]:
torch.abs(u).sum()

tensor(7.)

## 矩阵的*弗洛贝尼乌斯范数*（Frobenius norm）是矩阵元素的平凡和的平方根
$$
\begin{Vmatrix}
X
\end{Vmatrix}_F = \sqrt{\sum_{i=1}^m\sum_{j=1}^n{x_{ij}^2}}
$$

In [109]:
print(torch.norm(torch.ones((4,9))))
M1 = torch.ones((4,9))
M1

tensor(6.)


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])